### PR TITLE
Update to conda-build 3 and conda-smithy 3

### LINKED ISSUE #1: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #1.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #1

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@CJ-Wright, do we need to do anything extra for the bot to notice this requires a rebuild with the new compilers?

**Comment by CJ-Wright** [comment]
It looks good, let's see if the bot picks it up in 30 mins

**Comment by jakirkham** [comment]
Looks like it did. ( https://github.com/conda-forge/chrpath-feedstock/pull/3 ) 😄

**Comment by CJ-Wright** [comment]
Like magic :tada:

**Pull request merged**
